AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  BucketName:
    Type: String
  LinksFileKey:
    Type: String
Resources:
  ShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          LINKS_FILE_KEY: !Ref LinksFileKey
      Events:
        GetAlias:
          Type: Api
          Properties:
            Path: "/goto/{alias}"
            Method: get
